name = "RemoteFiles"
uuid = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
version = "0.3.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
FileIO = "≥ 1.0.1"
HTTP = "≥ 0.6.12"
julia = "≥ 0.7.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
